######################################################################
# Automatically generated by qmake (3.0) ?? ???. 23 13:03:39 2015
######################################################################

TEMPLATE = app
TARGET = MyDialog
INCLUDEPATH += .

# Input
HEADERS += MyDialog.h
SOURCES += main.cpp
